# Generated by Django 4.0.6 on 2022-07-28 12:55

from django.db import migrations, models
import django_bank_requisites.django_validators
import django_bank_requisites.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnvalidated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Legal address')),
                ('inn', models.CharField(max_length=12, unique=True, validators=[django_bank_requisites.django_validators.validate_inn], verbose_name='INN')),
                ('kpp', models.CharField(max_length=9, validators=[django_bank_requisites.django_validators.validate_kpp], verbose_name='KPP')),
                ('rs', models.CharField(max_length=20, unique=True, validators=[django_bank_requisites.django_validators.validate_rs], verbose_name='RS')),
                ('ks', models.CharField(blank=True, max_length=20, validators=[django_bank_requisites.django_validators.validate_ks], verbose_name='KS')),
                ('bik', models.CharField(max_length=9, validators=[django_bank_requisites.django_validators.validate_bik], verbose_name='BIK')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank name')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationValidated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Legal address')),
                ('inn', models.CharField(max_length=12, unique=True, validators=[django_bank_requisites.django_validators.validate_inn], verbose_name='INN')),
                ('kpp', models.CharField(max_length=9, validators=[django_bank_requisites.django_validators.validate_kpp], verbose_name='KPP')),
                ('rs', models.CharField(max_length=20, unique=True, validators=[django_bank_requisites.django_validators.validate_rs], verbose_name='RS')),
                ('ks', models.CharField(blank=True, max_length=20, validators=[django_bank_requisites.django_validators.validate_ks], verbose_name='KS')),
                ('bik', models.CharField(max_length=9, validators=[django_bank_requisites.django_validators.validate_bik], verbose_name='BIK')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank name')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization name')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_bank_requisites.mixins.SaveMethodMixin, models.Model),
        ),
    ]
